gText_Oak_Welcome::
	.string "Welcome back to the world of\n"
	.string "POKéMON! I'm PROF. OAK.\p"
	.string "My work in KANTO uncovered\n"
	.string "signs of ancient relics.$"

gText_Oak_Pokemon::
	.string "This UNOWN has been drawn\n"
	.string "to the strange activity.$"

gText_Oak_MainSpeech::
	.string "The Resonance I found didn't\n"
	.string "end in KANTO. It leads to\l"
	.string "JOHTO's ruins and symbols.\p"
	.string "Even the POKéMON there seem\n"
	.string "connected. PROF. ELM is\l"
	.string "studying them now.\p"
	.string "He needs someone he can trust\n"
	.string "to help him in JOHTO.$"

gText_Oak_AndYouAre::
	.string "And you are?$"

gText_Oak_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Oak_WhatChallenge::
	.string "What challenge are you\n"
	.string "expecting?$"

gText_Oak_ChallengeSelected::
	.string "That sounds like the right\n"
	.string "level of challenge to me!$" 

gText_Oak_WhatsYourName::
	.string "And what's your name?$"

gText_Oak_SoItsPlayer::
	.string "Oh! So you're {PLAYER}{KUN}?$"

gText_Oak_YourePlayer::
	.string "{PLAYER}{KUN}, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "$"

gText_Oak_AreYouReady::
	.string "You'll face fun times and tough\n"
	.string "challenges.\p"
	.string "A world of dreams and adventures\n"
	.string "with POKéMON awaits! Let's go!\p"
	.string "I'll be seeing you later!\p"
	.string "$"
