gText_Oak_Welcome::
	.string "Welcome to the world\n"
	.string "of POKéMON! I'm OAK.\p"
	.string "I study old relics\n"
	.string "and unusual POKéMON.$"

gText_Oak_Pokemon::
	.string "This is an UNOWN.\n"
	.string "It senses Resonance.$"

gText_Oak_MainSpeech::
	.string "A strange Resonance\n"
	.string "began in KANTO.\p"
	.string "Now it has reached\n"
	.string "JOHTO's ancient ruins.\p"
	.string "PROF. ELM needs help\n"
	.string "with his research.$"

gText_Oak_AndYouAre::
	.string "And you are?$"

gText_Oak_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Oak_WhatChallenge::
	.string "What kind of journey\n"
	.string "are you expecting?$"

gText_Oak_ChallengeSelected::
	.string "That sounds right.\n"
	.string "Your journey awaits!$"

gText_Oak_WhatsYourName::
	.string "And what's your name?$"

gText_Oak_SoItsPlayer::
	.string "So your name is\n"
	.string "{PLAYER}{KUN}?$"

gText_Oak_YourePlayer::
	.string "{PLAYER}{KUN}!\p"
	.string "Your journey begins\n"
	.string "in JOHTO.$"

gText_Oak_AreYouReady::
	.string "Meet POKéMON as you\n"
	.string "explore ancient JOHTO.\p"
	.string "Your adventure begins!\n"
	.string "I'll see you again.$"
