gText_Oak_Welcome::
	.string "Welcome to the world\n"
	.string "of POKéMON! I'm OAK.$"

gText_Oak_Pokemon::
	.string "This is an UNOWN.\n"
	.string "It senses Resonance.$"

gText_Oak_MainSpeech::
	.string "Old relics are stirring\n"
	.string "across JOHTO's ruins.$"

gText_Oak_AndYouAre::
	.string "And you are?$"

gText_Oak_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Oak_WhatChallenge::
	.string "What kind of journey\n"
	.string "are you expecting?$"

gText_Oak_ChallengeSelected::
	.string "That sounds right.\n"
	.string "Your journey awaits!$"

gText_Oak_WhatsYourName::
	.string "And what's your name?$"

gText_Oak_SoItsPlayer::
	.string "So your name is\n"
	.string "{PLAYER}{KUN}?$"

gText_Oak_YourePlayer::
	.string "{PLAYER}{KUN}!\n"
	.string "Your journey begins.$"

gText_Oak_AreYouReady::
	.string "Explore ancient JOHTO.\n"
	.string "Your adventure begins!$"
